// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Define the User message
type User struct {
	UserId               string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string               `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FullName             string               `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address              string               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PasswordHash         string               `protobuf:"bytes,6,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Email                string               `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// Request message for creating a user
type CreateUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PasswordHash         string   `protobuf:"bytes,5,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CreateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateUserRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateUserRequest) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// Response message for CreateUser
type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for retrieving a user by ID
type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// Response message for GetUser
type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for updating a user
type UpdateUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PasswordHash         string   `protobuf:"bytes,6,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Email                string   `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UpdateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UpdateUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UpdateUserRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpdateUserRequest) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// Response message for UpdateUser
type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for deleting a user
type DeleteUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CheckUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserRequest) Reset()         { *m = CheckUserRequest{} }
func (m *CheckUserRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUserRequest) ProtoMessage()    {}
func (*CheckUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *CheckUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserRequest.Unmarshal(m, b)
}
func (m *CheckUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserRequest.Marshal(b, m, deterministic)
}
func (m *CheckUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserRequest.Merge(m, src)
}
func (m *CheckUserRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUserRequest.Size(m)
}
func (m *CheckUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserRequest proto.InternalMessageInfo

func (m *CheckUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type CheckUserResponse struct {
	Status               int64            `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UserInfo             *RegisterRequest `protobuf:"bytes,4,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CheckUserResponse) Reset()         { *m = CheckUserResponse{} }
func (m *CheckUserResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUserResponse) ProtoMessage()    {}
func (*CheckUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *CheckUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserResponse.Unmarshal(m, b)
}
func (m *CheckUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserResponse.Marshal(b, m, deterministic)
}
func (m *CheckUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserResponse.Merge(m, src)
}
func (m *CheckUserResponse) XXX_Size() int {
	return xxx_messageInfo_CheckUserResponse.Size(m)
}
func (m *CheckUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserResponse proto.InternalMessageInfo

func (m *CheckUserResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CheckUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CheckUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CheckUserResponse) GetUserInfo() *RegisterRequest {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type RegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RegisterResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{12}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type LoginResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{13}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoginResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*CreateUserRequest)(nil), "auth.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "auth.CreateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "auth.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "auth.GetUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "auth.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "auth.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "auth.DeleteUserRequest")
	proto.RegisterType((*CheckUserRequest)(nil), "auth.CheckUserRequest")
	proto.RegisterType((*CheckUserResponse)(nil), "auth.CheckUserResponse")
	proto.RegisterType((*RegisterRequest)(nil), "auth.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "auth.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xfe, 0x9d, 0x38, 0xa7, 0x49, 0xfb, 0xb7, 0x5d, 0xda, 0xd4, 0x72, 0x25, 0x28, 0xe6, 0xa6,
	0x20, 0x94, 0x4a, 0x41, 0x42, 0x42, 0x08, 0x4a, 0x69, 0x11, 0x54, 0x42, 0xbd, 0x48, 0x29, 0x17,
	0xdc, 0x44, 0x9b, 0x7a, 0x12, 0x5b, 0x8d, 0x0f, 0x78, 0xd7, 0xa0, 0x4a, 0xbc, 0x03, 0x8f, 0xc3,
	0x13, 0x20, 0xde, 0x82, 0x67, 0x41, 0xbb, 0xeb, 0x8d, 0x1d, 0xa7, 0x27, 0x7a, 0x51, 0x89, 0xbb,
	0xcc, 0x7c, 0x33, 0xbb, 0xdf, 0x7c, 0x33, 0x3b, 0x0e, 0x00, 0x4d, 0xb9, 0xd7, 0x8d, 0x93, 0x88,
	0x47, 0xc4, 0x14, 0xbf, 0xed, 0x7b, 0xe3, 0x28, 0x1a, 0x4f, 0x70, 0x5b, 0xfa, 0x86, 0xe9, 0x68,
	0x9b, 0xfb, 0x01, 0x32, 0x4e, 0x83, 0x58, 0x85, 0xd9, 0x1b, 0xe5, 0x00, 0x0c, 0x62, 0x7e, 0xa6,
	0x40, 0xe7, 0x57, 0x05, 0xcc, 0x63, 0x86, 0x09, 0x59, 0x87, 0x46, 0xca, 0x30, 0x19, 0xf8, 0xae,
	0x65, 0x6c, 0x1a, 0x5b, 0xad, 0x7e, 0x5d, 0x98, 0x07, 0x2e, 0xd9, 0x80, 0x96, 0x04, 0x42, 0x1a,
	0xa0, 0x55, 0x91, 0x50, 0x53, 0x38, 0x0e, 0x69, 0x80, 0x02, 0x1c, 0xa5, 0x93, 0x89, 0x02, 0xab,
	0x0a, 0x14, 0x0e, 0x09, 0xde, 0x87, 0x85, 0xd8, 0x8b, 0x42, 0x1c, 0x84, 0x69, 0x30, 0xc4, 0xc4,
	0x32, 0x25, 0xde, 0x96, 0xbe, 0x43, 0xe9, 0x22, 0x16, 0x34, 0xa8, 0xeb, 0x26, 0xc8, 0x98, 0x55,
	0x93, 0xa8, 0x36, 0xc9, 0x03, 0x58, 0x8c, 0x29, 0x63, 0x5f, 0xa3, 0xc4, 0x1d, 0x78, 0x94, 0x79,
	0x56, 0x5d, 0xe2, 0x0b, 0xda, 0xf9, 0x8e, 0x32, 0x8f, 0xac, 0x42, 0x0d, 0x03, 0xea, 0x4f, 0xac,
	0x86, 0x04, 0x95, 0x41, 0x9e, 0x01, 0x9c, 0x24, 0x48, 0x39, 0xba, 0x03, 0xca, 0xad, 0xe6, 0xa6,
	0xb1, 0xd5, 0xee, 0xd9, 0x5d, 0xa5, 0x42, 0x57, 0xab, 0xd0, 0xfd, 0xa0, 0x65, 0xea, 0xb7, 0xb2,
	0xe8, 0x5d, 0x2e, 0x52, 0xd3, 0xd8, 0xd5, 0xa9, 0xad, 0xab, 0x53, 0xb3, 0xe8, 0x5d, 0xee, 0xfc,
	0x34, 0x60, 0x65, 0x4f, 0x1e, 0x24, 0xf4, 0xec, 0xe3, 0xe7, 0x14, 0x19, 0x9f, 0x55, 0xcf, 0xb8,
	0x4c, 0xbd, 0xca, 0x15, 0xea, 0x55, 0x2f, 0x55, 0xcf, 0xbc, 0x42, 0xbd, 0xda, 0x65, 0xea, 0xd5,
	0x0b, 0xea, 0x39, 0xdf, 0x80, 0x14, 0xcb, 0x60, 0x71, 0x14, 0x32, 0x24, 0x77, 0xc1, 0x14, 0xb4,
	0x65, 0x09, 0xed, 0x1e, 0x74, 0xe5, 0x18, 0xca, 0x08, 0xe9, 0x27, 0x1d, 0xa8, 0x33, 0x4e, 0x79,
	0xca, 0x64, 0x1d, 0xd5, 0x7e, 0x66, 0xc9, 0x3b, 0x92, 0x24, 0xd2, 0xf4, 0x95, 0x21, 0x88, 0x07,
	0xc8, 0x18, 0x1d, 0xa3, 0x26, 0x9e, 0x99, 0xce, 0x43, 0xf8, 0xff, 0x2d, 0xf2, 0xa2, 0x82, 0x17,
	0x0d, 0xa6, 0x73, 0x06, 0x4b, 0xd3, 0xd0, 0x5b, 0x66, 0xf9, 0xdb, 0x80, 0x95, 0x63, 0xd9, 0xf9,
	0xeb, 0x30, 0xfd, 0xf7, 0x9e, 0x90, 0x18, 0x82, 0x62, 0x7d, 0xb7, 0x2c, 0xef, 0x63, 0x58, 0xd9,
	0xc7, 0x09, 0x5e, 0x4f, 0x5d, 0xe7, 0x11, 0x2c, 0xef, 0x79, 0x78, 0x72, 0x5a, 0x0c, 0xee, 0x80,
	0x42, 0xf7, 0x67, 0x62, 0xf7, 0x9d, 0xef, 0xe2, 0x91, 0xe6, 0xc1, 0x59, 0x5d, 0x39, 0x6f, 0xe3,
	0x7c, 0xde, 0x95, 0x0b, 0x78, 0x57, 0x67, 0x78, 0x93, 0x5e, 0xd6, 0x67, 0x3f, 0x1c, 0x45, 0xb2,
	0xa6, 0x76, 0x6f, 0x4d, 0x89, 0xd4, 0xc7, 0xb1, 0xcf, 0xf8, 0x94, 0x9f, 0x6a, 0xff, 0x41, 0x38,
	0x8a, 0x9c, 0x00, 0x96, 0x4a, 0x20, 0x21, 0x60, 0x16, 0xd6, 0x85, 0xfc, 0x4d, 0x6c, 0x68, 0xea,
	0xb6, 0xe9, 0x09, 0xd2, 0xb6, 0xa0, 0x29, 0x07, 0x42, 0xcb, 0x2b, 0x8d, 0xbc, 0xb1, 0x66, 0xb1,
	0xb1, 0xaf, 0x60, 0x39, 0xbf, 0xee, 0x26, 0xe5, 0x3b, 0x1f, 0x61, 0xe1, 0x7d, 0x34, 0xf6, 0x43,
	0xcd, 0x76, 0x7a, 0x8f, 0x51, 0xdc, 0xc1, 0x7f, 0xcd, 0xd7, 0x39, 0x82, 0xc5, 0xec, 0xdc, 0x1b,
	0x75, 0x65, 0x15, 0x6a, 0x3c, 0x3a, 0xc5, 0x50, 0x1f, 0x2a, 0x8d, 0xde, 0x8f, 0x2a, 0xb4, 0x77,
	0x53, 0xee, 0x1d, 0x61, 0xf2, 0xc5, 0x3f, 0x41, 0xf2, 0x1c, 0x9a, 0xba, 0x7c, 0x72, 0x7e, 0x6b,
	0xec, 0x4e, 0xd9, 0xad, 0xe8, 0x38, 0xff, 0x91, 0x1e, 0xd4, 0x24, 0x43, 0x42, 0x54, 0x48, 0x51,
	0x06, 0xfb, 0xce, 0x8c, 0x6f, 0x9a, 0xf3, 0x12, 0x5a, 0xd3, 0x79, 0x23, 0xd9, 0xd1, 0xe5, 0x69,
	0xb5, 0xd7, 0xe7, 0xfc, 0xd3, 0xfc, 0x1d, 0x80, 0x7c, 0x1b, 0x13, 0x1d, 0x58, 0xfe, 0xcc, 0xd8,
	0xd6, 0x3c, 0x90, 0xa9, 0xf8, 0x14, 0x1a, 0xd9, 0x96, 0x24, 0xab, 0x2a, 0x68, 0x76, 0xbf, 0xda,
	0x6b, 0x25, 0x6f, 0x96, 0xb7, 0x03, 0x90, 0x6f, 0x00, 0x7d, 0xf1, 0xdc, 0xce, 0xd3, 0x17, 0x9f,
	0xb3, 0x2c, 0x5e, 0x00, 0xe4, 0x8f, 0x58, 0x1f, 0x30, 0xf7, 0xac, 0xed, 0xce, 0xdc, 0xd7, 0xf5,
	0x8d, 0xf8, 0x7b, 0xf2, 0xba, 0xfe, 0xc9, 0xec, 0x6e, 0xc7, 0xc3, 0x61, 0x5d, 0xfa, 0x9f, 0xfc,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x38, 0x1f, 0xf1, 0x76, 0xf9, 0x08, 0x00, 0x00,
}
