// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shop.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Define the Shop message
type Shop struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	OwnerId              string               `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{0}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shop) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Shop) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Shop) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Shop) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// Define the Product message
type Product struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId               string               `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Stock                int32                `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Price                float64              `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *Product) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Product) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// Request message for creating a shop
type CreateShopRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	OwnerId              string   `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShopRequest) Reset()         { *m = CreateShopRequest{} }
func (m *CreateShopRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShopRequest) ProtoMessage()    {}
func (*CreateShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{2}
}

func (m *CreateShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShopRequest.Unmarshal(m, b)
}
func (m *CreateShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShopRequest.Marshal(b, m, deterministic)
}
func (m *CreateShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShopRequest.Merge(m, src)
}
func (m *CreateShopRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShopRequest.Size(m)
}
func (m *CreateShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShopRequest proto.InternalMessageInfo

func (m *CreateShopRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateShopRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateShopRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

// Response message for CreateShop
type CreateShopResponse struct {
	Shop                 *Shop    `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShopResponse) Reset()         { *m = CreateShopResponse{} }
func (m *CreateShopResponse) String() string { return proto.CompactTextString(m) }
func (*CreateShopResponse) ProtoMessage()    {}
func (*CreateShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{3}
}

func (m *CreateShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShopResponse.Unmarshal(m, b)
}
func (m *CreateShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShopResponse.Marshal(b, m, deterministic)
}
func (m *CreateShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShopResponse.Merge(m, src)
}
func (m *CreateShopResponse) XXX_Size() int {
	return xxx_messageInfo_CreateShopResponse.Size(m)
}
func (m *CreateShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShopResponse proto.InternalMessageInfo

func (m *CreateShopResponse) GetShop() *Shop {
	if m != nil {
		return m.Shop
	}
	return nil
}

func (m *CreateShopResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateShopResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateShopResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for updating a shop
type UpdateShopRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	OwnerId              string   `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateShopRequest) Reset()         { *m = UpdateShopRequest{} }
func (m *UpdateShopRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateShopRequest) ProtoMessage()    {}
func (*UpdateShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{4}
}

func (m *UpdateShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateShopRequest.Unmarshal(m, b)
}
func (m *UpdateShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateShopRequest.Marshal(b, m, deterministic)
}
func (m *UpdateShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateShopRequest.Merge(m, src)
}
func (m *UpdateShopRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateShopRequest.Size(m)
}
func (m *UpdateShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateShopRequest proto.InternalMessageInfo

func (m *UpdateShopRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateShopRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateShopRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpdateShopRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

// Response message for UpdateShop
type UpdateShopResponse struct {
	Shop                 *Shop    `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateShopResponse) Reset()         { *m = UpdateShopResponse{} }
func (m *UpdateShopResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateShopResponse) ProtoMessage()    {}
func (*UpdateShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{5}
}

func (m *UpdateShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateShopResponse.Unmarshal(m, b)
}
func (m *UpdateShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateShopResponse.Marshal(b, m, deterministic)
}
func (m *UpdateShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateShopResponse.Merge(m, src)
}
func (m *UpdateShopResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateShopResponse.Size(m)
}
func (m *UpdateShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateShopResponse proto.InternalMessageInfo

func (m *UpdateShopResponse) GetShop() *Shop {
	if m != nil {
		return m.Shop
	}
	return nil
}

func (m *UpdateShopResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateShopResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateShopResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for retrieving a shop by ID
type GetShopRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopRequest) Reset()         { *m = GetShopRequest{} }
func (m *GetShopRequest) String() string { return proto.CompactTextString(m) }
func (*GetShopRequest) ProtoMessage()    {}
func (*GetShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{6}
}

func (m *GetShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopRequest.Unmarshal(m, b)
}
func (m *GetShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopRequest.Marshal(b, m, deterministic)
}
func (m *GetShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopRequest.Merge(m, src)
}
func (m *GetShopRequest) XXX_Size() int {
	return xxx_messageInfo_GetShopRequest.Size(m)
}
func (m *GetShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopRequest proto.InternalMessageInfo

func (m *GetShopRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Response message for GetShop
type GetShopResponse struct {
	Shop                 *Shop    `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShopResponse) Reset()         { *m = GetShopResponse{} }
func (m *GetShopResponse) String() string { return proto.CompactTextString(m) }
func (*GetShopResponse) ProtoMessage()    {}
func (*GetShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{7}
}

func (m *GetShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShopResponse.Unmarshal(m, b)
}
func (m *GetShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShopResponse.Marshal(b, m, deterministic)
}
func (m *GetShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShopResponse.Merge(m, src)
}
func (m *GetShopResponse) XXX_Size() int {
	return xxx_messageInfo_GetShopResponse.Size(m)
}
func (m *GetShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShopResponse proto.InternalMessageInfo

func (m *GetShopResponse) GetShop() *Shop {
	if m != nil {
		return m.Shop
	}
	return nil
}

func (m *GetShopResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetShopResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetShopResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for listing all shops
type ListShopsRequest struct {
	OwnerId              string   `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListShopsRequest) Reset()         { *m = ListShopsRequest{} }
func (m *ListShopsRequest) String() string { return proto.CompactTextString(m) }
func (*ListShopsRequest) ProtoMessage()    {}
func (*ListShopsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{8}
}

func (m *ListShopsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShopsRequest.Unmarshal(m, b)
}
func (m *ListShopsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShopsRequest.Marshal(b, m, deterministic)
}
func (m *ListShopsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShopsRequest.Merge(m, src)
}
func (m *ListShopsRequest) XXX_Size() int {
	return xxx_messageInfo_ListShopsRequest.Size(m)
}
func (m *ListShopsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShopsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListShopsRequest proto.InternalMessageInfo

func (m *ListShopsRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

// Response message for ListShops
type ListShopsResponse struct {
	Shops                []*Shop  `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListShopsResponse) Reset()         { *m = ListShopsResponse{} }
func (m *ListShopsResponse) String() string { return proto.CompactTextString(m) }
func (*ListShopsResponse) ProtoMessage()    {}
func (*ListShopsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{9}
}

func (m *ListShopsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShopsResponse.Unmarshal(m, b)
}
func (m *ListShopsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShopsResponse.Marshal(b, m, deterministic)
}
func (m *ListShopsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShopsResponse.Merge(m, src)
}
func (m *ListShopsResponse) XXX_Size() int {
	return xxx_messageInfo_ListShopsResponse.Size(m)
}
func (m *ListShopsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShopsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListShopsResponse proto.InternalMessageInfo

func (m *ListShopsResponse) GetShops() []*Shop {
	if m != nil {
		return m.Shops
	}
	return nil
}

func (m *ListShopsResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListShopsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListShopsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for deleting a shop
type DeleteShopRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShopRequest) Reset()         { *m = DeleteShopRequest{} }
func (m *DeleteShopRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShopRequest) ProtoMessage()    {}
func (*DeleteShopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{10}
}

func (m *DeleteShopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShopRequest.Unmarshal(m, b)
}
func (m *DeleteShopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShopRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShopRequest.Merge(m, src)
}
func (m *DeleteShopRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShopRequest.Size(m)
}
func (m *DeleteShopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShopRequest proto.InternalMessageInfo

func (m *DeleteShopRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Request message for creating a product
type CreateProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Stock                int32    `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Price                float64  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{11}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateProductRequest) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *CreateProductRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

// Response message for CreateProduct
type CreateProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{12}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

func (m *CreateProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *CreateProductResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateProductResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateProductResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for updating a product
type UpdateProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId               string   `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Stock                int32    `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Price                float64  `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{13}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProductRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *UpdateProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProductRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateProductRequest) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *UpdateProductRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

// Response message for UpdateProduct
type UpdateProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{14}
}

func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

func (m *UpdateProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *UpdateProductResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateProductResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateProductResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for retrieving a product by ID
type GetProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId               string   `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{15}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetProductRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

// Response message for GetProduct
type GetProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{16}
}

func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (m *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(m, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *GetProductResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetProductResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetProductResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for listing all products in a shop
type ListProductsRequest struct {
	ShopId               string   `protobuf:"bytes,1,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductsRequest) Reset()         { *m = ListProductsRequest{} }
func (m *ListProductsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductsRequest) ProtoMessage()    {}
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{17}
}

func (m *ListProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsRequest.Unmarshal(m, b)
}
func (m *ListProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsRequest.Marshal(b, m, deterministic)
}
func (m *ListProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsRequest.Merge(m, src)
}
func (m *ListProductsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductsRequest.Size(m)
}
func (m *ListProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsRequest proto.InternalMessageInfo

func (m *ListProductsRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

// Response message for ListProducts
type ListProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Status               int64      `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Message              string     `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProductsResponse) Reset()         { *m = ListProductsResponse{} }
func (m *ListProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductsResponse) ProtoMessage()    {}
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{18}
}

func (m *ListProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsResponse.Unmarshal(m, b)
}
func (m *ListProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsResponse.Marshal(b, m, deterministic)
}
func (m *ListProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsResponse.Merge(m, src)
}
func (m *ListProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductsResponse.Size(m)
}
func (m *ListProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsResponse proto.InternalMessageInfo

func (m *ListProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *ListProductsResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListProductsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListProductsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Request message for deleting a product
type DeleteProductRequest struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ShopId               string   `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{19}
}

func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *DeleteProductRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

// Define the DeleteShopResponse message
type DeleteShopResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShopResponse) Reset()         { *m = DeleteShopResponse{} }
func (m *DeleteShopResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteShopResponse) ProtoMessage()    {}
func (*DeleteShopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f3030369b20fd61, []int{20}
}

func (m *DeleteShopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShopResponse.Unmarshal(m, b)
}
func (m *DeleteShopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShopResponse.Marshal(b, m, deterministic)
}
func (m *DeleteShopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShopResponse.Merge(m, src)
}
func (m *DeleteShopResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteShopResponse.Size(m)
}
func (m *DeleteShopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShopResponse proto.InternalMessageInfo

func (m *DeleteShopResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteShopResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteShopResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Shop)(nil), "shop.Shop")
	proto.RegisterType((*Product)(nil), "shop.Product")
	proto.RegisterType((*CreateShopRequest)(nil), "shop.CreateShopRequest")
	proto.RegisterType((*CreateShopResponse)(nil), "shop.CreateShopResponse")
	proto.RegisterType((*UpdateShopRequest)(nil), "shop.UpdateShopRequest")
	proto.RegisterType((*UpdateShopResponse)(nil), "shop.UpdateShopResponse")
	proto.RegisterType((*GetShopRequest)(nil), "shop.GetShopRequest")
	proto.RegisterType((*GetShopResponse)(nil), "shop.GetShopResponse")
	proto.RegisterType((*ListShopsRequest)(nil), "shop.ListShopsRequest")
	proto.RegisterType((*ListShopsResponse)(nil), "shop.ListShopsResponse")
	proto.RegisterType((*DeleteShopRequest)(nil), "shop.DeleteShopRequest")
	proto.RegisterType((*CreateProductRequest)(nil), "shop.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "shop.CreateProductResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "shop.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "shop.UpdateProductResponse")
	proto.RegisterType((*GetProductRequest)(nil), "shop.GetProductRequest")
	proto.RegisterType((*GetProductResponse)(nil), "shop.GetProductResponse")
	proto.RegisterType((*ListProductsRequest)(nil), "shop.ListProductsRequest")
	proto.RegisterType((*ListProductsResponse)(nil), "shop.ListProductsResponse")
	proto.RegisterType((*DeleteProductRequest)(nil), "shop.DeleteProductRequest")
	proto.RegisterType((*DeleteShopResponse)(nil), "shop.DeleteShopResponse")
}

func init() {
	proto.RegisterFile("shop.proto", fileDescriptor_0f3030369b20fd61)
}

var fileDescriptor_0f3030369b20fd61 = []byte{
	// 788 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x5d, 0x4f, 0x13, 0x4d,
	0x14, 0xce, 0x74, 0xfb, 0x41, 0x4f, 0x5f, 0x78, 0xed, 0x58, 0x60, 0x59, 0xa2, 0x36, 0xeb, 0x85,
	0x78, 0xe1, 0x92, 0x60, 0x62, 0x62, 0x42, 0x42, 0x10, 0x09, 0x92, 0x18, 0x63, 0x16, 0xbd, 0x31,
	0x24, 0x64, 0xe9, 0x8e, 0xb0, 0x91, 0x76, 0xd7, 0x9d, 0xa9, 0x86, 0x44, 0x2f, 0x4d, 0xd4, 0x7f,
	0xe1, 0x95, 0xbf, 0xc8, 0xff, 0x63, 0xe6, 0xab, 0x3b, 0xfb, 0x41, 0x09, 0x04, 0xe1, 0xae, 0x73,
	0xe6, 0xcc, 0x99, 0xe7, 0x79, 0xe6, 0x7c, 0x6c, 0x01, 0xe8, 0x71, 0x9c, 0x78, 0x49, 0x1a, 0xb3,
	0x18, 0xd7, 0xf9, 0x6f, 0xe7, 0xde, 0x51, 0x1c, 0x1f, 0x9d, 0x90, 0x55, 0x61, 0x3b, 0x1c, 0xbf,
	0x5f, 0x65, 0xd1, 0x90, 0x50, 0x16, 0x0c, 0x95, 0x9b, 0xb3, 0x5c, 0x74, 0x20, 0xc3, 0x84, 0x9d,
	0xca, 0x4d, 0xf7, 0x0f, 0x82, 0xfa, 0xde, 0x71, 0x9c, 0xe0, 0x39, 0xa8, 0x45, 0xa1, 0x8d, 0xfa,
	0x68, 0xa5, 0xed, 0xd7, 0xa2, 0x10, 0x63, 0xa8, 0x8f, 0x82, 0x21, 0xb1, 0x6b, 0xc2, 0x22, 0x7e,
	0x63, 0x1b, 0x5a, 0x41, 0x18, 0xa6, 0x84, 0x52, 0xdb, 0x12, 0x66, 0xbd, 0xc4, 0x4b, 0x30, 0x13,
	0x7f, 0x1e, 0x91, 0xf4, 0x20, 0x0a, 0xed, 0xba, 0xdc, 0x12, 0xeb, 0xdd, 0x10, 0x3f, 0x05, 0x18,
	0xa4, 0x24, 0x60, 0x24, 0x3c, 0x08, 0x98, 0xdd, 0xe8, 0xa3, 0x95, 0xce, 0x9a, 0xe3, 0x49, 0x4c,
	0x9e, 0xc6, 0xe4, 0xbd, 0xd1, 0xa0, 0xfd, 0xb6, 0xf2, 0xde, 0x64, 0xfc, 0xe8, 0x38, 0x09, 0xf5,
	0xd1, 0xe6, 0xf9, 0x47, 0x95, 0xf7, 0x26, 0x73, 0x7f, 0xd6, 0xa0, 0xf5, 0x3a, 0x8d, 0xc3, 0xf1,
	0x80, 0x95, 0xa8, 0x2d, 0x42, 0x8b, 0x2b, 0xc7, 0xb1, 0x4a, 0x76, 0x4d, 0xbe, 0xdc, 0xcd, 0x38,
	0x5b, 0x06, 0xe7, 0x3e, 0x74, 0x42, 0x42, 0x07, 0x69, 0x94, 0xb0, 0x28, 0x1e, 0x29, 0x72, 0xa6,
	0x09, 0xf7, 0xa0, 0x41, 0x59, 0x3c, 0xf8, 0x20, 0xb8, 0x35, 0x7c, 0xb9, 0xe0, 0xd6, 0x24, 0x8d,
	0x06, 0x44, 0xc0, 0x46, 0xbe, 0x5c, 0x14, 0xc4, 0x68, 0x5d, 0x5e, 0x8c, 0x99, 0x8b, 0x88, 0xb1,
	0x0f, 0xdd, 0x2d, 0x11, 0x87, 0xbf, 0xb4, 0x4f, 0x3e, 0x8e, 0x09, 0x65, 0x13, 0xb2, 0xa8, 0xfa,
	0x81, 0x6b, 0x67, 0x3f, 0xb0, 0x95, 0x7b, 0x60, 0xf7, 0x0b, 0x60, 0x33, 0x3a, 0x4d, 0xe2, 0x11,
	0x25, 0xf8, 0x2e, 0x88, 0xf4, 0x14, 0xe1, 0x3b, 0x6b, 0xe0, 0x89, 0xbc, 0x15, 0x1e, 0xc2, 0x8e,
	0x17, 0xa0, 0x49, 0x59, 0xc0, 0xc6, 0xf2, 0x26, 0xcb, 0x57, 0x2b, 0xae, 0x1b, 0x49, 0xd3, 0x38,
	0x55, 0xb7, 0xc8, 0x05, 0x07, 0x36, 0x24, 0x94, 0x06, 0x47, 0x44, 0xa7, 0x97, 0x5a, 0xba, 0x27,
	0xd0, 0x7d, 0x2b, 0x88, 0x9a, 0xdc, 0xfe, 0x55, 0x32, 0x73, 0xae, 0xe6, 0x6d, 0xd7, 0xcc, 0xb5,
	0x0f, 0x73, 0x3b, 0x84, 0x4d, 0x21, 0xea, 0x9e, 0xc2, 0xff, 0x13, 0x8f, 0x6b, 0x06, 0xf7, 0x08,
	0x6e, 0xbd, 0x8c, 0xa8, 0xb8, 0x9b, 0x6a, 0x78, 0xa6, 0x92, 0x28, 0xaf, 0xe4, 0x57, 0xe8, 0x1a,
	0xee, 0x0a, 0x6b, 0x1f, 0x1a, 0x1c, 0x13, 0xb5, 0x51, 0xdf, 0x2a, 0x80, 0x95, 0x1b, 0x57, 0x86,
	0xf6, 0x3e, 0x74, 0x9f, 0x93, 0x13, 0x32, 0x35, 0x6d, 0xdc, 0xef, 0x08, 0x7a, 0x32, 0xb5, 0x55,
	0x2b, 0xb9, 0x48, 0x7e, 0x15, 0x1a, 0x87, 0x35, 0xa5, 0x71, 0xd4, 0x2b, 0x1b, 0x47, 0xc3, 0x68,
	0x1c, 0x1c, 0xca, 0x7c, 0x01, 0x8a, 0xd2, 0xec, 0x01, 0xb4, 0x12, 0x69, 0x52, 0x4f, 0x3c, 0x2b,
	0x55, 0xd3, 0x7e, 0x7a, 0xf7, 0xca, 0xa4, 0xfb, 0x85, 0xa0, 0x27, 0x8b, 0xe0, 0x1c, 0x55, 0x6e,
	0xae, 0xcf, 0x0a, 0xb9, 0x0a, 0x18, 0x6f, 0x4a, 0xae, 0x75, 0xe8, 0xee, 0x10, 0x76, 0x49, 0xa9,
	0xdc, 0x6f, 0x08, 0xb0, 0x79, 0xfc, 0xa6, 0x58, 0x78, 0x70, 0x9b, 0x97, 0xab, 0x8a, 0x3f, 0x29,
	0x70, 0x03, 0x37, 0xca, 0xe1, 0xfe, 0x81, 0xa0, 0x97, 0x3f, 0xa0, 0x90, 0x3f, 0x84, 0x19, 0x85,
	0x4d, 0x57, 0x79, 0x01, 0xfa, 0x64, 0xfb, 0xca, 0xb0, 0xbf, 0x82, 0x9e, 0xac, 0xf5, 0xc2, 0x23,
	0xdc, 0x01, 0x50, 0x77, 0x65, 0xf8, 0xdb, 0xca, 0xb2, 0x3b, 0xe5, 0x4d, 0xf6, 0x01, 0x9b, 0xbd,
	0x43, 0x11, 0xcb, 0xd0, 0xa2, 0x6a, 0xb4, 0xb5, 0x33, 0xd0, 0x5a, 0x39, 0xb4, 0x6b, 0xbf, 0x1b,
	0xd0, 0xe1, 0x81, 0xf7, 0x48, 0xfa, 0x89, 0x7f, 0x32, 0x6c, 0x00, 0x64, 0xe3, 0x15, 0x2f, 0x4a,
	0xb1, 0x4a, 0xe3, 0xdc, 0xb1, 0xcb, 0x1b, 0x0a, 0xd8, 0x06, 0x40, 0x36, 0xb3, 0x74, 0x80, 0xd2,
	0xcc, 0xd4, 0x01, 0x2a, 0xc6, 0xdb, 0x13, 0x68, 0xa9, 0xa1, 0x82, 0x7b, 0xd2, 0x29, 0x3f, 0x85,
	0x9c, 0xf9, 0x82, 0x55, 0x9d, 0x5b, 0x87, 0xf6, 0xa4, 0xc5, 0xe3, 0x05, 0xe9, 0x53, 0x1c, 0x11,
	0xce, 0x62, 0xc9, 0x9e, 0xc1, 0xce, 0x54, 0xd6, 0xb0, 0x4b, 0x3d, 0x5b, 0xc3, 0xae, 0x78, 0x90,
	0x17, 0x30, 0x9b, 0xeb, 0x98, 0xd8, 0x31, 0x25, 0xca, 0xe7, 0x82, 0xb3, 0x5c, 0xb9, 0x97, 0x45,
	0xca, 0x35, 0x13, 0x1d, 0xa9, 0xaa, 0x0b, 0xea, 0x48, 0xd5, 0xdd, 0x67, 0x03, 0x20, 0xab, 0x66,
	0x4d, 0xaa, 0xd4, 0x1e, 0x34, 0xa9, 0x8a, 0xc2, 0xdf, 0x86, 0xff, 0xcc, 0xb2, 0xc2, 0x4b, 0x99,
	0x7c, 0x85, 0xda, 0x74, 0x9c, 0xaa, 0x2d, 0x15, 0x66, 0x0b, 0x66, 0x73, 0x25, 0xa1, 0x19, 0x55,
	0xd5, 0x89, 0xb3, 0x50, 0xfa, 0xca, 0xdc, 0xe6, 0xff, 0x20, 0x9e, 0x35, 0xdf, 0xd5, 0xbd, 0xd5,
	0xe4, 0xf0, 0xb0, 0x29, 0xec, 0x8f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x4c, 0xef, 0x05,
	0x9c, 0x0c, 0x00, 0x00,
}
